# Generated by Django 3.2.16 on 2023-01-10 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=11)),
                ('web', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event_date', models.DateTimeField()),
                ('manager', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('attendee', models.ManyToManyField(to='event.ClubAttendee')),
                ('venue_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.venue')),
            ],
        ),
    ]
