# Generated by Django 3.2.16 on 2023-01-25 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20230125_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubattendee',
            name='food_choice',
            field=models.ForeignKey(default='veg', on_delete=django.db.models.deletion.CASCADE, to='event.foodchoice'),
        ),
    ]
