# Generated by Django 3.2.16 on 2023-01-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
    ]
